### PR TITLE
Fix desktop file Exec for devel builds

### PR DESCRIPTION
**Pull request by kra-mo**

### CODE REVIEW

**Comment by kra-mo** [comment]
For some reason, while the command is now valid, the app still doesn't launch from the app grid. `gtk-launch`/`gtk4-launch` exit cleanly when I pass in `com.vixalien.decibelsDevel` as an argument, but the app doesn't start. `gio launch` does work with the absolute path to the file though, so I have no idea what the issue is there.

**Review by vixalien — APPROVED** [review]

**Comment by vixalien** [comment]
thanks

**Comment by kra-mo** [comment]
> For some reason, while the command is now valid, the app still doesn't launch from the app grid.

@vixalien Actually, this has nothing to do with your app, it just seems like something broke in Fedora.

**Comment by kra-mo** [comment]
@vixalien Nevermind nevermind. Both of these are true :p. It does have something to do with your app.

**Comment by vixalien** [comment]
okay. Ill take a look soon

**Comment by vixalien** [comment]
the issue should be fixed now

**Pull request merged**
